/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneoRouteImport } from './routes/torneo'
import { Route as RegolamentoRouteImport } from './routes/regolamento'
import { Route as IscrizioneRouteImport } from './routes/iscrizione'
import { Route as GestioneRouteImport } from './routes/gestione'
import { Route as IndexRouteImport } from './routes/index'

const TorneoRoute = TorneoRouteImport.update({
  id: '/torneo',
  path: '/torneo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegolamentoRoute = RegolamentoRouteImport.update({
  id: '/regolamento',
  path: '/regolamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IscrizioneRoute = IscrizioneRouteImport.update({
  id: '/iscrizione',
  path: '/iscrizione',
  getParentRoute: () => rootRouteImport,
} as any)
const GestioneRoute = GestioneRouteImport.update({
  id: '/gestione',
  path: '/gestione',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestione': typeof GestioneRoute
  '/iscrizione': typeof IscrizioneRoute
  '/regolamento': typeof RegolamentoRoute
  '/torneo': typeof TorneoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestione': typeof GestioneRoute
  '/iscrizione': typeof IscrizioneRoute
  '/regolamento': typeof RegolamentoRoute
  '/torneo': typeof TorneoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestione': typeof GestioneRoute
  '/iscrizione': typeof IscrizioneRoute
  '/regolamento': typeof RegolamentoRoute
  '/torneo': typeof TorneoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gestione' | '/iscrizione' | '/regolamento' | '/torneo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gestione' | '/iscrizione' | '/regolamento' | '/torneo'
  id:
    | '__root__'
    | '/'
    | '/gestione'
    | '/iscrizione'
    | '/regolamento'
    | '/torneo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestioneRoute: typeof GestioneRoute
  IscrizioneRoute: typeof IscrizioneRoute
  RegolamentoRoute: typeof RegolamentoRoute
  TorneoRoute: typeof TorneoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneo': {
      id: '/torneo'
      path: '/torneo'
      fullPath: '/torneo'
      preLoaderRoute: typeof TorneoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regolamento': {
      id: '/regolamento'
      path: '/regolamento'
      fullPath: '/regolamento'
      preLoaderRoute: typeof RegolamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iscrizione': {
      id: '/iscrizione'
      path: '/iscrizione'
      fullPath: '/iscrizione'
      preLoaderRoute: typeof IscrizioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestione': {
      id: '/gestione'
      path: '/gestione'
      fullPath: '/gestione'
      preLoaderRoute: typeof GestioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestioneRoute: GestioneRoute,
  IscrizioneRoute: IscrizioneRoute,
  RegolamentoRoute: RegolamentoRoute,
  TorneoRoute: TorneoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
